### PR TITLE
Add link to Whitepaper v2

### PR DESCRIPTION
**Pull request by Varunram**

### CODE REVIEW

**Comment by jjenzz** [comment]
Deploy preview ready!

Built with commit dd3c49d958cd0bdaf932a065c07085045a618d22

https://deploy-preview-65--clerk-falls-n9urbglepegngpivyxxrrned.netlify.com

**Comment by Varunram** [comment]
Yep, looks good :)

**Comment by Varunram** [comment]
Please don't merge, there are a few changes going on :)

**Comment by Varunram** [comment]
Forgot about this. Updated!

**Comment by Varunram** [comment]
Closing this since I added the commit to another PR.

**Pull request closed without merging**
